# ✅ FIXED - SCENARIO 9: ENVIRONMENT DEPLOYMENT ERRORS
# Fixes: Proper environment references, stage dependencies, deployment jobs, environment variables

trigger:
  branches:
    include:
      - main

# Fixed: Environment-specific variables defined at pipeline level
variables:
  buildConfig: 'Release'
  # These would typically come from variable groups or environment variables
  devApiUrl: 'https://api-dev.example.com'
  stagingApiUrl: 'https://api-staging.example.com'
  prodApiUrl: 'https://api.example.com'

stages:
  - stage: Build
    displayName: 'Build Application'
    jobs:
      - job: BuildJob
        displayName: 'Build and Test'
        pool:
          name: 'Default'
        steps:
          - task: UseDotNet@2
            displayName: 'Install .NET'
            inputs:
              version: '6.x'

          - task: DotNetCoreCLI@2
            displayName: 'Build Project'
            inputs:
              command: 'build'
              projects: 'test-project/BuildTestApp.csproj'
              configuration: $(buildConfig)

          - task: DotNetCoreCLI@2
            displayName: 'Publish Artifacts'
            inputs:
              command: 'publish'
              projects: 'test-project/BuildTestApp.csproj'
              arguments: '--configuration $(buildConfig) --output $(Build.ArtifactStagingDirectory)'
              publishWebProjects: false

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Build Artifacts'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'

  # Fixed: Stage dependency on Build stage
  - stage: Deploy_Dev
    displayName: 'Deploy to Development'
    dependsOn: Build
    jobs:
      # Fixed: Using deployment job type with environment reference
      - deployment: DeployDevJob
        displayName: 'Deploy to Dev Environment'
        pool:
          name: 'Default'
        # Fixed: Reference to Development environment (enables approvals, tracking)
        environment: 'Development'
        strategy:
          runOnce:
            deploy:
              steps:
                # Fixed: Download artifacts from Build stage
                - task: DownloadBuildArtifacts@1
                  displayName: 'Download Artifacts'
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: 'drop'
                    downloadPath: '$(System.ArtifactsDirectory)'

                - script: |
                    echo "Deploying to Development environment"
                    echo "Configuration: $(buildConfig)"
                    echo "API URL: $(devApiUrl)"
                    echo "Artifacts downloaded to: $(System.ArtifactsDirectory)"
                  displayName: 'Simulate Dev Deployment'

  - stage: Deploy_Staging
    displayName: 'Deploy to Staging'
    # Fixed: Correct dependency name matching the stage name
    dependsOn: Deploy_Dev
    jobs:
      # Fixed: Using deployment job type with environment reference
      - deployment: DeployStagingJob
        displayName: 'Deploy to Staging Environment'
        pool:
          name: 'Default'
        # Fixed: Reference to Staging environment
        environment: 'Staging'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@1
                  displayName: 'Download Artifacts'
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: 'drop'
                    downloadPath: '$(System.ArtifactsDirectory)'

                - script: |
                    echo "Deploying to Staging environment"
                    echo "Configuration: $(buildConfig)"
                    echo "API URL: $(stagingApiUrl)"
                    echo "Artifacts downloaded to: $(System.ArtifactsDirectory)"
                  displayName: 'Simulate Staging Deployment'

  - stage: Deploy_Production
    displayName: 'Deploy to Production'
    # Fixed: Dependency on Deploy_Staging stage
    dependsOn: Deploy_Staging
    # Fixed: Condition to ensure staging deployment succeeded
    condition: succeeded('Deploy_Staging')
    jobs:
      # Fixed: Using deployment job type with environment reference
      - deployment: DeployProdJob
        displayName: 'Deploy to Production Environment'
        pool:
          name: 'Default'
        # Fixed: Reference to Production environment (can have manual approvals)
        environment: 'Production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@1
                  displayName: 'Download Artifacts'
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: 'drop'
                    downloadPath: '$(System.ArtifactsDirectory)'

                - script: |
                    echo "Deploying to Production environment"
                    echo "Configuration: $(buildConfig)"
                    echo "API URL: $(prodApiUrl)"
                    echo "Artifacts downloaded to: $(System.ArtifactsDirectory)"
                    echo "🚀 Production deployment complete!"
                  displayName: 'Simulate Production Deployment'
