#test comment
trigger:
  - none

pool:
  name: 'Default'

variables:
  buildConfiguration: 'Release'
  testProjectPath: 'test-project'

jobs:
  - job: Build
    displayName: 'Build Test Application'
    steps:
      - task: UseDotNet@2
        displayName: 'Install .NET SDK'
        inputs:
          version: '6.x'

      - task: DotNetCoreCLI@2
        displayName: 'Restore NuGet packages'
        inputs:
          command: 'restore'
          projects: '$(testProjectPath)/*.csproj'

      - task: DotNetCoreCLI@2
        displayName: 'Build application'
        inputs:
          command: 'build'
          projects: '$(testProjectPath)/BuildTestApp.csproj'
          arguments: '--configuration $(buildConfiguration)'

      - task: DotNetCoreCLI@2
        displayName: 'Run application tests'
        inputs:
          command: 'run'
          projects: '$(testProjectPath)/BuildTestApp.csproj'

  - job: PublishArtifact
    displayName: 'Publish Build Output'
    dependsOn: Build
    condition: succeeded()
    steps:
      - task: DotNetCoreCLI@2
        displayName: 'Publish application'
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: '$(testProjectPath)/BuildTestApp.csproj'
          arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Upload artifacts'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'app-$(Build.BuildNumber)'
          publishLocation: 'Container'
