# ❌ BROKEN - SCENARIO 5A: TRIGGER SYNTAX ERRORS
# Common Issue: ~10% of pipeline support tickets
# Error Type: Invalid trigger syntax, conflicting schedules, bad branch patterns

trigger:
  - main

pr:
  - main
  branches:
    include:
      - feature/*
    exclude:
      - feature/experimental

schedules:
  - cron: "0 2 * * 1-5"
    displayName: 'Daily build'
    branches:
      include:
        - main
      exclude:
        - main
    always: true

variables:
  buildConfig: 'Release'

jobs:
  - job: Build
    displayName: 'Simple Build'
    steps:
      - script: echo "Building on trigger"